{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_base.TestDemo1 object at 0x0000019FCC2D6EE0>\n\n    def test_two(self):\n        print(\"test_two\")\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\npython_code\\pytest_code\\test_base.py:20: AssertionError"}, "start": 1735537089382, "stop": 1735537089382, "uuid": "aa74b753-a938-4cbe-b994-5ade1f3b4d8d", "historyId": "6f8e24cda5f092483e931e7eb37ba424", "testCaseId": "6f8e24cda5f092483e931e7eb37ba424", "fullName": "python_code.pytest_code.test_base.TestDemo1#test_two", "labels": [{"name": "parentSuite", "value": "python_code.pytest_code"}, {"name": "suite", "value": "test_base"}, {"name": "subSuite", "value": "TestDemo1"}, {"name": "host", "value": "DESKTOP-ATVCHDC"}, {"name": "thread", "value": "6304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python_code.pytest_code.test_base"}]}